//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mp3tagtools.rc
//
#define IDM_ABOUTBOX                    0x0010
//#define RT_MANIFEST                     24
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MP3TAGTOOLS_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_SAPREFS                     129
#define IDD_PREFS_PAGE1                 130
#define IDR_LIST_MENU                   135
#define IDD_ID3V2_DIALOG                136
#define IDD_ID3V2LIST_DIALOG            137
#define IDD_MPEGINFO_DIALOG             138
#define IDD_CUSTOM_FORMAT_DIALOG        140
#define IDR_BLANKIMAGE                  140
#define IDD_DIR_DIALOG                  141
#define IDD_ID3V1_DIALOG                142
#define IDD_LYRICS_DIALOG               143
#define IDD_ID3V1LIST_DIALOG            144
#define IDR_MAINDLG_MENU                144
#define IDD_PICTURE_DIALOG              145
#define IDD_OPENFILE_TEMPLATE           146
#define IDR_MAINDLG_ACCELERATOR         146
#define IDD_PREFS_ID3V1EXPORTPAGE       150
#define IDD_PREFS_ID3V2EXPORTPAGE       151
#define IDD_PREFS_ID3V1HIDEPAGE         152
#define IDD_PREFS_ID3V2HIDEPAGE         153
#define IDD_PREFS_PAGE2                 154
#define IDD_PREFS_CORRECTCASEPAGE       155
#define IDD_PREFS_MISC                  156
#define IDD_PREFS_COLORPAGE             157
#define IDD_PREFS_GENRE                 158
#define IDD_PREFS_COPYTAGSPAGE          159
#define IDD_PPAGE_FILENAMEFORMAT        160
#define IDD_PPAGE_DIRECTORYFORMAT       161
#define IDD_PPAGE_FILERENAME            162
#define IDC_TITLE_EDIT                  1000
#define IDC_ARTIST_EDIT                 1001
#define IDC_ALBUM_EDIT                  1002
#define IDC_YEAR_EDIT                   1003
#define IDC_GENRE_COMBO                 1004
#define IDC_DLG_FRAME                   1004
#define IDC_COMMENT_EDIT                1005
#define IDC_TRACK_EDIT                  1006
#define IDC_PATH_BUTTON                 1008
#define IDC_FILEPATH_EDIT               1008
#define IDC_EDIT1                       1008
#define IDC_PICDESCRIPTION_EDIT         1008
#define IDC_LEADZERO_EDIT1              1008
#define IDC_CASESYMBOLS_EDIT            1008
#define IDC_PATH_EDIT                   1009
#define IDC_CAPTION_BAR                 1009
#define IDC_EDIT3                       1009
#define IDC_PREFIXWORDS_EDIT            1009
#define IDC_LEADZERO_CHECK              1010
#define IDC_PAGE_TREE                   1010
#define IDC_EDIT4                       1010
#define IDC_UPPERCASEWORDS_EDIT         1010
#define IDC_APPENDBIT_CHECK             1011
#define IDC_PHELP                       1011
#define IDC_EDIT5                       1011
#define IDC_LOWERCASEWORDS_EDIT         1011
#define IDC_TAGINFO_STATIC              1012
#define IDC_APPENDMODE_CHECK            1012
#define IDC_MPEGINFO_STATIC             1015
#define IDC_TAGFORMAT_STATIC            1016
#define IDC_GENRE_STATIC                1017
#define IDC_TITLE_STATIC                1018
#define IDC_ARTIST_STATIC               1019
#define IDC_ALBUM_STATIC                1021
#define IDC_RECURSECHK                  1022
#define IDC_YEAR_STATIC                 1022
#define IDC_COMMENT_STATIC              1023
#define IDC_TITLECHK                    1024
#define IDC_ARTISTCHK                   1025
#define IDC_ALBUMCHK                    1026
#define IDC_YEARCHK                     1027
#define IDC_GENRECHK                    1028
#define IDC_COMMENTCHK                  1029
#define IDC_TRACKCHK                    1030
#define IDC_CUSTOM_FORMATCHK            1031
#define IDC_CUSTOMFORMAT_EDIT           1032
#define IDC_CUSTOMFORMAT_BUTTON         1033
#define IDC_TRACK_STATIC                1034
#define IDC_DIROPTION_CHECK             1034
#define IDC_DIRFORMAT_COMBO             1035
#define IDC_SIZE_STATIC                 1036
#define IDC_LENGTH_STATIC               1037
#define IDC_VERSION_STATIC              1038
#define IDC_VERSIONDATA_STATIC          1038
#define IDC_BITRATE_STATIC              1039
#define IDC_FREQUENCY_STATIC            1040
#define IDC_CRC_STATIC                  1041
#define IDC_COPYRIGHT_STATIC            1042
#define IDC_MP3VIEW_LIST                1043
#define IDC_ORIGINAL_STATIC             1044
#define IDC_PROGRESSBAR                 1045
#define IDC_EMPHASIS_STATIC             1046
#define IDC_MODE_STATIC                 1047
#define IDC_SIZEDATA_STATIC             1048
#define IDC_ABOUT_BUTTON                1049
#define IDC_MOVEUP_BUTTON               1049
#define IDC_BITRATEDATA_STATIC          1050
#define IDC_EXIT_BUTTON                 1051
#define IDC_WRITETAGS_BUTTON            1052
#define IDC_ARTISTFORMAT_CHK            1053
#define IDC_CRCDATA_STATIC              1053
#define IDC_TITLEFORMAT_CHK             1054
#define IDC_LENGTHDATA_STATIC           1054
#define IDC_ALBUMFORMAT_CHK             1055
#define IDC_FREQUENCYDATA_STATIC        1055
#define IDC_YEARFORMAT_CHK              1056
#define IDC_COPYRIGHTDATA_STATIC        1056
#define IDC_COMMENTFORMAT_CHK           1057
#define IDC_ORIGINALDATA_STATIC         1057
#define IDC_TRACKFORMAT_CHK             1058
#define IDC_MODEDATA_STATIC             1058
#define IDC_FORMATVIEW_EDIT             1059
#define IDC_EMPHASISDATA_STATIC         1059
#define IDC_SEPARATOR_EDIT              1060
#define IDC_TAGINFO_TAB                 1060
#define IDC_EMPTY_BUTTON                1061
#define IDC_MOVEDOWN_BUTTON             1061
#define IDC_REMOVE_BUTTON               1062
#define IDC_SELECTALL_BUTTON            1062
#define IDC_REFRESH_BUTTON              1063
#define IDC_REMOVEALL_BUTTON            1063
#define IDC_ID3V1VIEW_LIST              1063
#define IDC_ID3V2VIEW_LIST              1064
#define IDC_PICTURE_STATIC              1064
#define IDC_SEPARATOR_EDIT2             1064
#define IDC_DIR_BUTTON                  1065
#define IDC_OPEN_BUTTON                 1065
#define IDC_SEPARATOR_EDIT3             1065
#define IDC_FORMATVIEW_LIST             1066
#define IDC_LOAD_BUTTON                 1066
#define IDC_STATUS_STATIC               1067
#define IDC_SEPARATOR_EDIT4             1067
#define IDC_PERCENT_STATIC              1068
#define IDC_PICTYPE_COMBO               1068
#define IDC_SEPARATOR_EDIT5             1068
#define IDC_RENAMEFILES_BUTTON          1069
#define IDC_CORRECT_BUTTON              1070
#define IDC_CREATEDIR_BUTTON            1070
#define IDC_CLEAN_FILENAMES_BUTTON      1071
#define IDC_REMOVEPIC_BUTTON            1071
#define IDC_PICTYPE_STATIC              1072
#define IDC_LISTVIEWMARKER_STATIC       1073
#define IDC_PICDESCRIPTION_STATIC       1073
#define IDC_LYRICS_EDIT                 1074
#define IDC_ORGANIZEFILES_BUTTON        1075
#define IDC_LEADZERO_EDIT2              1076
#define IDC_STATICURL_PROJECTPAGE       1077
#define IDC_STATICURL_HOME              1078
#define IDC_STATICURL_ID3LIB            1079
#define IDC_STATICURL_EMAIL             1080
#define IDC_INVERT_BUTTON               1081
#define IDS_CASESYMBOLS                 1081
#define IDC_ALL_BUTTON                  1082
#define IDC_UP_BUTTON                   1082
#define IDS_DELIMITERS                  1082
#define IDC_NONE_BUTTON                 1083
#define IDC_DOWN_BUTTON                 1083
#define IDS_LOWERCASEWORDS              1083
#define IDC_ADD_BUTTON                  1084
#define IDS_PREFIXWORDS                 1084
#define IDC_ADDALL_BUTTON               1085
#define IDS_UPPERCASEWORDS              1085
#define IDC_SHOWCOL_LIST                1086
#define IDS_ERROR_FILENOTFOUND          1086
#define IDC_HIDECOL_LIST                1087
#define IDC_SELCOL_LIST                 1088
#define IDC_LIST1                       1089
#define IDC_AVAILCOL_LIST               1089
#define IDC_LIST2                       1090
#define IDC_PROMPT_CHECK                1090
#define IDC_BUTTON1                     1091
#define IDC_TIMESTAMP_CHECK             1091
#define IDC_USEDEFAULTS_BUTTON          1091
#define IDC_ID3V1FILECOLOR_BUTTON       1091
#define IDC_USEFOLDER_BUTTON            1091
#define IDC_BUTTON2                     1092
#define IDC_SEPARATOR_EDIT_PREFIX       1092
#define IDC_ID3V1FILETEXTCOLOR_BUTTON   1092
#define IDC_AUTOLOADLASTDIR_CHECK       1092
#define IDC_CURRENTFOLDER_BUTTON        1092
#define IDC_BUTTON3                     1093
#define IDC_SEPARATOR_EDIT_SUFFIX       1093
#define IDC_ID3V2FILECOLOR_BUTTON       1093
#define IDC_INVERTSEL_BUTTON            1093
#define IDC_USEINFO_BUTTON              1093
#define IDC_BUTTON4                     1094
#define IDC_IGNORE_BUTTON               1094
#define IDC_ID3V2FILETEXTCOLOR_BUTTON   1094
#define IDC_BUTTON5                     1095
#define IDC_ID3V1NOTAGCOLOR_BUTTON      1095
#define IDC_ARTISTFORMAT_BUTTON         1095
#define IDC_BUTTON6                     1096
#define IDC_ID3V1NOTAGTEXTCOLOR_BUTTON  1096
#define IDC_ALBUMFORMAT_BUTTON          1096
#define IDC_SEPARATOR_COMBO             1097
#define IDC_ID3V2NOTAGCOLOR_BUTTON      1097
#define IDC_BUTTON7                     1098
#define IDC_ID3V2NOTAGTEXTCOLOR_BUTTON  1098
#define IDC_YEARFORMAT_BUTTON           1098
#define IDC_FILENAMEFORMAT_EDIT         1099
#define IDC_ADDSEPARATOR_BUTTON         1100
#define IDC_STOREFORMAT_BUTTON          1101
#define IDC_EMPTYFORMAT_BUTTON          1102
#define IDC_EDITFORMAT_BUTTON           1103
#define IDC_DELETEFORMAT_BUTTON         1104
#define IDC_FILENAMEFORMAT_COMBO        1105
#define IDC_RICHEDIT1                   1107
#define IDC_ID3V1FILECOLOR_STATIC       1110
#define IDC_ID3V1FILETEXTCOLOR_STATIC   1111
#define IDC_ID3V2FILECOLOR_STATIC       1112
#define IDC_ID3V2FILETEXTCOLOR_STATIC   1113
#define IDC_ID3V1NOTAGCOLOR_STATIC      1114
#define IDC_ID3V1NOTAGTEXTCOLOR_STATIC  1115
#define IDC_ID3V2NOTAGCOLOR_STATIC      1116
#define IDC_ID3V2NOTAGTEXTCOLOR_STATIC  1117
#define IDC_USEDEFAULTCOLORS_BUTTON     1118
#define IDC_DONTUSECOLORS_BUTTON        1119
#define IDC_FILENAMEFORMAT_LIST         1120
#define IDC_MISCFORMAT_COMBO            1122
#define IDC_COMMENTFORMAT_BUTTON        1123
#define IDC_GENREFORMAT_BUTTON          1124
#define IDC_ADDBSLASH_BUTTON            1125
#define IDC_DIRECTORYFORMAT_LIST        1126
#define IDC_DIRECTORYFORMAT_EDIT        1127
#define ID_FILE_PLAY                    32782
#define ID_FILE_WRITETAGS               32786
#define ID_FILE_RENAMEFILES             32787
#define ID_FILE_REMOVETAGS              32788
#define ID_FILE_CLEANFILENAMES          32789
#define ID_FILE_OPENFILEDIR             32790
#define ID_FILE_REFRESHLIST             32792
#define ID_FILE_ENQUEUE                 32793
#define ID_FILE_SELECTALLITEMS          32794
#define ID_FILE_EXPORTDATA              32795
#define ID_ALLMUSIC_ARTIST              32797
#define ID_ALLMUSIC_ALBUM               32798
#define ID_ALLMUSIC_TITLE               32799
#define ID_FILE_COPYV1TOV2              32800
#define ID_FILE_SYNCHRONIZE             32801
#define ID_FILE_COPYV2TOV1              32802
#define ID_FILE_REMOVENONID3TAGS        32803
#define ID_FILE_DELETEFILE              32804
#define ID_FILE_PREFS                   32805
#define ID_FILE_EXIT                    32807
#define ID_VIEW_REFRESH                 32808
#define ID_HELP_ABOUTMP3TAGTOOLS        32809
#define ID_HELP_CONTENTSANDINDEX        32810
#define ID_TOOLS_PROGRAMPREFERENCES     32811
#define ID_OPTIONS_PROGRAMPREFERENCES   32811
#define ID_EDIT_SELECTALL               32812
#define ID_FILE_OPENDIRECTORY           32813
#define ID_VIEW_ID3V11                  32814
#define ID_VIEW_ID3V2X                  32815
#define ID_VIEW_LYRICS                  32816
#define ID_VIEW_PICTURE                 32817
#define ID_TOOLS_EXPORTDATA             32818
#define ID_TOOLS_CREATEDIRECTORY        32819
#define ID_TOOLS_CLEANFILENAMES         32820
#define ID_EDIT_EMPTY                   32821
#define ID_TOOLS_COPYV1TOV2             32822
#define ID_TOOLS_COPYV2TOV1             32823
#define ID_TOOLS_SYNCHRONIZE            32824
#define ID_EDIT_CORRECTCASE             32825
#define ID_EDIT_SELECTALLFIELDS         32826
#define ID_EDIT_SELECTNONEOFTHEFIELDS   32827
#define ID_EDIT_INVERTFIELDSELECTION    32828
#define ID_EDIT_FORMATOPTIONS           32829
#define ID_OPTIONS_FORMATOPTIONS        32829
#define ID_EDIT_WRITETAGS               32830
#define ID_EDIT_REMOVETAGS              32831
#define ID_EDIT_USEFILENAMEFORMAT       32832
#define ID_OPTIONS_USEFILENAMEFORMAT    32832
#define ID_EDIT_USEDIRECTORYFORMAT      32833
#define ID_OPTIONS_USEDIRECTORYFORMAT   32833
#define ID_TOOLS_REMOVENONID3TAGS       32834
#define ID_TOOLS_ALLMUSIC_ARTIST        32835
#define ID_TOOLS_ALLMUSIC_ALBUM         32836
#define ID_TOOLS_ALLMUSIC_TITLE         32837
#define ID_VIEW_SWITCHWINDOWFOCUS       32838
#define ID_EDIT_INVERTSELECTION         32839
#define ID_FILE_INVERTSELECTION         32840
#define ID_TOOLS_CORRECTCASEOFTAGS      32841
#define ID_OPTIONS_CORRECTCASEOPTIONS   32842
#define ID_OPTIONS_COPYTAGSOPTIONS      32843
#define ID_OPTIONS_EXPORTTAGSOPTIONS    32844
#define ID_TOOLS_CLEANID3V11TAGS        32845

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32846
#define _APS_NEXT_CONTROL_VALUE         1128
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
